### PR TITLE
Fix some typos in the README file

### PR DESCRIPTION
**Pull request by mahezer**
Hey, just fixed some typos in your README file. Great repo, thanks for sharing =).

### CODE REVIEW

**Comment by brunoti** [comment]
Thank you for the contribution!

**Comment by brunoti** [comment]
Please put some picture on your profile and start making contributions too.

**Comment by brunoti** [comment]
:heart:

**Comment by mahezer** [comment]
<3
NO

**Comment by brunoti** [comment]
:-1:

**Pull request merged**
